/*
 * One cycle: reads -> assembly (miassembler) -> MAGs (genomes-generation).
 *
 * Called once per cycle with a different reads channel; aliasing the import gives each
 * cycle its own process instances (see main.nf).
 *
 * `bins` and not `mags`: GGP's `mags` are dereplicated across everything in the same run,
 * so in cycle 2 the n=1 / n=5 / n=10 genomes of one organism would collapse into a single
 * representative and the comparison would lose its slots. `bins` are the per-run
 * dereplicated, QS50 filtered genomes - one set per dataset, which is the unit this
 * experiment compares.
 */

include { SHORT_READS_ASSEMBLER } from '../../../pipelines/miassembler/workflows/short_reads_assembler'
include { GGP                   } from '../../../pipelines/genomes-generation/workflows/ggp'

workflow ASSEMBLE_AND_BIN {

    take:
    reads  // channel: [ val(meta), [ path(fastq_1), path(fastq_2) ] ]

    main:
    SHORT_READS_ASSEMBLER( reads )

    /*
     * GGP takes [ meta, assembly, [ reads ] ].
     *
     * Joined on `meta.id`, not on the meta map: SHORT_READS_ASSEMBLER rewrites the meta
     * it was given (`meta + [assembler: "metaspades", assembler_version: ...]`), so the
     * map that comes back out is never equal to the one that went in and a plain
     * `join(reads)` silently matches nothing - which is exactly how a run once got all
     * the way to COMPARE having assembled a sample and produced no MAG at all.
     *
     * The enriched meta is the one kept: assembly_software below needs its assembler.
     */
    assembly_and_reads = SHORT_READS_ASSEMBLER.out.cleaned_contigs
        .map { meta, assembly -> [meta.id, meta, assembly] }
        .join( reads.map { meta, fastqs -> [meta.id, fastqs] } )
        .map { _id, meta, assembly, fastqs -> [meta, assembly, fastqs] }

    /*
     * An assembly that found no reads means that join broke again. Deliberately not
     * `ifEmpty`: a cycle with nothing in it at all is legitimate - cycle 2 gets no
     * datasets when no cycle-1 MAG carried the target taxid - and `ifEmpty` also fires as
     * noise while the session is aborting for an unrelated reason.
     */
    assembly_and_reads.count()
        .combine( SHORT_READS_ASSEMBLER.out.cleaned_contigs.count() )
        .subscribe { joined, assembled ->
            if ( joined < assembled ) {
                error "${assembled - joined} of ${assembled} assemblies could not be joined back to their reads; the meta join in assemble_and_bin.nf is broken."
            }
        }

    // replaces GGP's SAMPLESHEET_GENERATION: only the uploader reads this file
    assembly_software = assembly_and_reads
        .collectFile(name: 'assembly_software.tsv', newLine: true) { meta, _assembly, _reads ->
            "${meta.id}\t${meta.assembler}_v${meta.assembler_version}"
        }

    GGP(
        assembly_and_reads,
        Channel.empty(),  // concoct bins, generated by GGP itself
        Channel.empty(),  // metabat bins
        Channel.empty(),  // maxbin bins
        Channel.empty(),  // jgi depth
        assembly_software
    )

    emit:
    assemblies = SHORT_READS_ASSEMBLER.out.cleaned_contigs   // [ val(meta), path(fa.gz) ]
    bins       = GGP.out.euk_bins.flatten()                  // path(fa.gz), named <meta.id>_<binner>_<n>.fa.gz
    versions   = SHORT_READS_ASSEMBLER.out.versions.mix( GGP.out.versions )
}
